"""added missing payment relationship

Revision ID: 039e37b04b30
Revises: 1d1e6e58fb32
Create Date: 2025-09-23 10:32:07.557052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039e37b04b30'
down_revision: Union[str, None] = '1d1e6e58fb32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
