"""tune payments model

Revision ID: 0f8a91364a74
Revises: 67a3c83eecac
Create Date: 2025-09-29 12:32:32.075764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8a91364a74'
down_revision: Union[str, None] = '67a3c83eecac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_currency', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('stripe_period_start', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('stripe_period_end', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('stripe_invoice_id', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('stripe_customer_email', sa.String(), nullable=False))
    op.alter_column('payments', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'stripe_payment_intent_id')
    op.drop_column('payments', 'stripe_charge_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_charge_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('stripe_payment_intent_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('payments', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('payments', 'stripe_customer_email')
    op.drop_column('payments', 'stripe_invoice_id')
    op.drop_column('payments', 'stripe_period_end')
    op.drop_column('payments', 'stripe_period_start')
    op.drop_column('payments', 'stripe_currency')
    # ### end Alembic commands ###
