"""added missing relationships v2

Revision ID: 1d1e6e58fb32
Revises: 37fa307bce5a
Create Date: 2025-09-23 10:29:04.301992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1e6e58fb32'
down_revision: Union[str, None] = '37fa307bce5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
