"""added missing relationships

Revision ID: 37fa307bce5a
Revises: cd42a8e8d0d2
Create Date: 2025-09-23 10:23:24.375288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37fa307bce5a'
down_revision: Union[str, None] = 'cd42a8e8d0d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
