"""features from dict to list

Revision ID: 59fc9f4c6241
Revises: 098991955538
Create Date: 2025-09-23 14:06:00.236837

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "59fc9f4c6241"
down_revision: Union[str, None] = "098991955538"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "member_profile", "birthday", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "member_profile", "address", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "member_profile", "zip_code", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "member_profile", "phone_number", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "member_profile",
        "gender",
        existing_type=postgresql.ENUM("MALE", "FEMALE", "OTHER", name="membergender"),
        nullable=False,
    )
    op.alter_column(
        "subscription_plans", "is_popular", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "subscription_plans",
        "features",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscription_plans",
        "features",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "subscription_plans", "is_popular", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "member_profile",
        "gender",
        existing_type=postgresql.ENUM("MALE", "FEMALE", "OTHER", name="membergender"),
        nullable=True,
    )
    op.alter_column(
        "member_profile", "phone_number", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "member_profile", "zip_code", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "member_profile", "address", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "member_profile", "birthday", existing_type=sa.DATE(), nullable=True
    )
    # ### end Alembic commands ###
