"""simplify payments model

Revision ID: 67a3c83eecac
Revises: f0d3aafed2ef
Create Date: 2025-09-25 15:17:04.393395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a3c83eecac'
down_revision: Union[str, None] = 'f0d3aafed2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_member_id', table_name='payments')
    op.drop_constraint('payments_member_id_fkey', 'payments', type_='foreignkey')
    op.drop_column('payments', 'member_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('payments_member_id_fkey', 'payments', 'member_profile', ['member_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_payments_member_id', 'payments', ['member_id'], unique=False)
    # ### end Alembic commands ###
