"""proper types for numbers

Revision ID: 7acdd3b5b3a1
Revises: 0f8a91364a74
Create Date: 2025-09-29 14:03:15.100960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7acdd3b5b3a1'
down_revision: Union[str, None] = '0f8a91364a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
