"""add user enum pending

Revision ID: 915056af824b
Revises: 79ad1e039408
Create Date: 2025-09-25 12:07:03.000597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "915056af824b"
down_revision: Union[str, None] = "79ad1e039408"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the 'memberstate' enum type
    op.execute("ALTER TYPE memberstate ADD VALUE 'PENDING'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
