"""members fk assigned

Revision ID: 95fb02848267
Revises: 6b72d73ebb24
Create Date: 2025-09-22 15:44:14.270605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95fb02848267"
down_revision: Union[str, None] = "6b72d73ebb24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "member_profile", sa.Column("member_auth_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None,
        "member_profile",
        "member_auth",
        ["member_auth_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "member_profile", type_="foreignkey")
    op.drop_column("member_profile", "member_auth_id")
    # ### end Alembic commands ###
