"""add stripe fields

Revision ID: 96d690648094
Revises: 59fc9f4c6241
Create Date: 2025-09-24 13:10:20.719723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96d690648094'
down_revision: Union[str, None] = '59fc9f4c6241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_payment_intent_id', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('stripe_charge_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('stripe_customer_id', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('status', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('currency', sa.String(), nullable=False))
    op.alter_column('subscription_plans', 'features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plans', 'features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'status')
    op.drop_column('payments', 'stripe_subscription_id')
    op.drop_column('payments', 'stripe_customer_id')
    op.drop_column('payments', 'stripe_charge_id')
    op.drop_column('payments', 'stripe_payment_intent_id')
    # ### end Alembic commands ###
