"""move fields from profile to auth

Revision ID: e58ef6e69d30
Revises: 039e37b04b30
Create Date: 2025-09-23 10:39:19.187100

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e58ef6e69d30"
down_revision: Union[str, None] = "039e37b04b30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "member_auth",
        sa.Column(
            "role",
            sa.Enum("SYSTEM_ADMIN", "TENANT_ADMIN", "STAFF", "MEMBER", name="role"),
            nullable=False,
        ),
    )
    op.add_column(
        "member_auth",
        sa.Column(
            "state",
            sa.Enum("ACTIVE", "CANCELLED", "SUSPENDED", "PAUSED", name="memberstate"),
            nullable=False,
        ),
    )
    op.drop_column("member_profile", "role")
    op.drop_column("member_profile", "state")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "member_profile",
        sa.Column(
            "state",
            postgresql.ENUM(
                "ACTIVE", "CANCELLED", "SUSPENDED", "PAUSED", name="memberstate"
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "member_profile",
        sa.Column(
            "role",
            postgresql.ENUM(
                "SYSTEM_ADMIN", "TENANT_ADMIN", "STAFF", "MEMBER", name="role"
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("member_auth", "state")
    op.drop_column("member_auth", "role")
    # ### end Alembic commands ###
