"""end_Date to be nullable

Revision ID: f0d3aafed2ef
Revises: 915056af824b
Create Date: 2025-09-25 12:44:01.459305

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f0d3aafed2ef"
down_revision: Union[str, None] = "915056af824b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "memberships", "end_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )

    # Change the 'status' column in 'payments' table from str to enum
    payment_status_enum = postgresql.ENUM(
        "PENDING", "COMPLETED", "FAILED", "REFUNDED", name="paymentstatus"
    )
    payment_status_enum.create(op.get_bind(), checkfirst=True)
    op.execute(
        """
        ALTER TABLE payments
        ALTER COLUMN status
        TYPE paymentstatus
        USING status::paymentstatus
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE payment
        ALTER COLUMN status
        TYPE VARCHAR
        USING status::TEXT
        """
    )

    # ### end Alembic commands ###
